# Generated by Django 5.2.5 on 2025-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
